---
- name: ajout depot dotdeb
  apt_repository: repo="{{ item }}"
  with_items:
    - deb http://packages.dotdeb.org jessie all
    - deb-src http://packages.dotdeb.org jessie all

- name: ajout clef
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg


- name: apt update_cache
  apt: update_cache=yes

- name: installation php_packages
  apt: name={{ item }} state=latest
  with_items: "{{ php_packages }}"


- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size= {{ php_post_max_size }}'
- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='memory_limit[\s]?=' line='memory_limit= {{ php_memory_limit }}'
- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='upload_max_filesize[\s]?=' line='upload_max_filesize= {{ php_upload_max_filesize }}'
- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.timezone[\s]?=' line='date.timezone= {{ php_timezone }}'
  notify: php restart
