---
- name: creation du dossier {{ item.domain }}
  become: yes
  when: item.repo is undefined
  file: path=/home/{{ user }}/{{ item.domain }} state=directory owner={{ user }}

- name: clonage du site {{ item.domain }} avec {{ item.repo }}
  become: yes
  when: item.repo is defined
  git: dest=/home/{{ user }}/{{ item.domain }} clone=yes repo={{ item.repo }}

- name : lien vers www {{ item.domain }}
  become: yes
  file: src=/home/{{ user }}/{{ item.domain }} dest=/var/www/{{ item.domain }} state=link

- name: creation configuration nginx
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ item.domain }} force=yes

- name: activation site {{ item.domain }}
  file: src=/etc/nginx/sites-available/{{ item.domain }} dest=/etc/nginx/sites-enabled/{{ item.domain }} state=link
  notify: nginx reloaded
...
